### ISSUE TITLE
Jira, incremental load not working?

### ISSUE THREAD

**Issue by robinmuilwijk** [grimoirelab/GrimoireELK#77]
If a run that command, to load Jira issues twice.... first for project EZS, and then with the same command but for project EZP, it should add all Jira issues in the same indexes right?

`p2o.py --enrich --index jira_raw --index-enrich jira -e http://localhost:9200 --debug jira https://jira.ez.no --project EZS`

and

`p2o.py --enrich --index jira_raw --index-enrich jira -e http://localhost:9200 --debug jira https://jira.ez.no --project EZP`

For some reason, it will only load data on the first command. The second run, it says it has not found any issues. Could it be due to an incorrect date somewhere, as in the index is marked somehow for incremental import?

I had this in my terminal:

(grimoirelab) gelk@grim:~$ p2o.py --enrich --index jira_raw --index-enrich jira -e http://localhost:9200 --no_inc --debug jira https://jira.ez.no --project EZP -u ****** -p '******'
2017-03-02 20:22:59,804 Debug mode activated
2017-03-02 20:23:18,942 Feeding Ocean from jira (https://jira.ez.no)
2017-03-02 20:23:19,253 http://localhost:9200/jira_raw/_search
        { "size": 0,
                "query" : {
                    "term" : { "tag" : "https://jira.ez.no"  }
                 },
             
            "aggs": {
                "1": {
                  "max": {
                    "field": "metadata__updated_on"
                  }
                }
            }
       
        }
2017-03-02 20:23:19,316 Incremental from: 2017-03-02 16:51:41+00:00
2017-03-02 20:23:19,317 Looking for issues at site 'https://jira.ez.no', in project 'EZP' and updated from '2017-03-02 16:51:41'
2017-03-02 20:23:20,499 No issues were found.

Am I doing something wrong? I also tried by adding the --no_inc as parameter on both commands.

**Comment by acs** [comment]
The problem is that for incremental update of an index, in order to find the last date for items already indexed, gelk uses as filter for items in Elastic Search the field **tag**. If you don't add the tag param as a perceval param, it uses origin as tag. So for EZS and EZP the tag is the same. And in this case, when trying to get the last item indexed from EZP, the search in Elastic Search returns also the EZS items, so the the last item already indexed date is "2017-03-02 16:51:41+00:00" and after that date, EZP does no have any issue.

The solution is to add the tag param to perceval, so items from EZS and EZP are tagged differently. 

`p2o.py --enrich --index jira_raw --index-enrich jira -e http://localhost:9200 --debug jira https://jira.ez.no --project EZS  --tag https://jira.ez.no/EZS
`

`p2o.py --enrich --index jira_raw --index-enrich jira -e http://localhost:9200 --debug jira https://jira.ez.no --project EZP  --tag https://jira.ez.no/EZP
`

@robinmuilwijk is that fixing your issue?

**Comment by robinmuilwijk** [comment]
I was actually going to double check on some kind of wrong 'filtering' assumption on my end. I thought I might have to skip the --project param. But this tag makes perfect sense. 

I will reload the data, using these commands, and let you know if it works. / @acs

**Comment by robinmuilwijk** [comment]
@acs I was able to load both Jira projects, adding the tag to the command worked. Thanks again for your help.
